Models/Reservation.cs
using System;

namespace AsinTransientAndApartment.Models
{
    public class Reservation
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public DateTime CheckInDate { get; set; }
        public DateTime CheckOutDate { get; set; }
        public int NumberOfGuest { get; set; }
        public int RoomId { get; set; }
        public DateTime CheckInTime { get; set; }
        public DateTime CheckOutTime { get; set; }
        public int ProcessedBy { get; set; }
        public DateTime ProcessedDate { get; set; }
        public string Comment { get; set; }
    }
}

Controllers/AsinController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AsinTransientAndApartment.Controllers
{
    public class AsinController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/GuestController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AsinTransientAndApartment.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Type = AsinTransientAndApartment.Models.Type;

namespace AsinTransientAndApartment.Controllers
{
    public class GuestController : Controller
    {
        private readonly ReservationDBContext _DB;
        public GuestController(ReservationDBContext DB)
        {
            _DB = DB;
        }
        public IQueryable<Reserve> reserves => _DB.Reserve;
        public IActionResult Index()
        {
            return View();
        }
        //public IActionResult GetTypes()
        //{
        //    var createTest = new Type
        //    {
        //        Name = "test"
        //    };
        //    _DB.types.Add(createTest);
        //    _DB.SaveChanges();
        //    var model = _DB.types.Where(x => x.Name == "test").ToList();
        //    return Json(model);
        //}
        public IActionResult AddGuest(string firstName, string lastName, string contactNumber, int numberOfGuest, int numberOfNight, Reserve createTest)
        {
            var test = new Guest
            {
                FirstName = firstName,
                LastName = lastName,
                ContactNumber = contactNumber,
                NumberOfGuest = numberOfGuest,
                NumberOfNight = numberOfNight
            };
            _DB.Reserve.Add(createTest);
            _DB.SaveChanges();
            var model = _DB.Reserve.Where(x => x.FirstName == firstName).ToList();
            return Json(model);
        }

        public IActionResult AddGuestById(int id)
        {
            Guest model = _DB.guests.Where(x => x.Id == id).FirstOrDefault();
            _DB.guests.Attach(model);
            _DB.SaveChanges();
            return Json(model);

        }
        //public IActionResult DeleteType()
        //{
        //    Type model = _DB.types.Where(x => x.Name == "test").FirstOrDefault();
        //    _DB.types.Remove(model);
        //    _DB.SaveChanges();
        //    return Json(model);

        //}
        //public IActionResult DeleteTypeById(int id)
        //{
        //    Type model = _DB.types.Where(x => x.Id == id).FirstOrDefault();
        //    _DB.types.Remove(model);
        //    _DB.SaveChanges();
        //    return Json(model);

        //}
        //public IActionResult LoadTypes()
        //{
        //    List<Type> typeList = _DB.types.Where(x => x.Name != null).ToList();
        //    return Json(typeList);
        //}
        //public IActionResult EditTypeById(string name, int id)
        //{
        //    Type model = _DB.types.Where(x => x.Id == id).FirstOrDefault();
        //    model.Name = name;
        //    _DB.types.Update(model);
        //    _DB.SaveChanges();
        //    return Json(model);

        //}
    }
}

Controllers/TypeController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AsinTransientAndApartment.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Type = AsinTransientAndApartment.Models.Type;

namespace AsinTransientAndApartment.Controllers
{
    public class TypeController : Controller
    {
        private readonly ReservationDBContext _DB;
        public TypeController(ReservationDBContext DB)
        {
            _DB = DB;
        }
        public IQueryable<Type> types => _DB.types;
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetTypes()
        {
            var createTest = new Type
            {
                Name = "test"
            };
            _DB.types.Add(createTest);
            _DB.SaveChanges();
            var model = _DB.types.Where(x => x.Name == "test").ToList();
            return Json(model);
        }
        public IActionResult InsertType(string name)
        {
            var createTest = new Type
            {
                Name = name
            };
            _DB.types.Add(createTest);
            _DB.SaveChanges();
            var model = _DB.types.Where(x => x.Name == name).ToList();
            return Json(model);
        }
        public IActionResult DeleteType()
        {
            Type model = _DB.types.Where(x => x.Name == "test").FirstOrDefault();
            _DB.types.Remove(model);
            _DB.SaveChanges();
            return Json(model);

        }
        public IActionResult DeleteTypeById(int id)
        {
            Type model = _DB.types.Where(x => x.Id == id).FirstOrDefault();
            _DB.types.Remove(model);
            _DB.SaveChanges();
            return Json(model);

        }
        public IActionResult LoadTypes()
        {
            List<Type> typeList = _DB.types.Where(x => x.Name != null).ToList();
            return Json(typeList);
        }
        public IActionResult EditTypeById(string name, int id)
        {
            Type model = _DB.types.Where(x => x.Id == id).FirstOrDefault();
            model.Name = name;
            _DB.types.Update(model);
            _DB.SaveChanges();
            return Json(model);

        }
    }
}

Views/Asin/AboutUs.cshtml
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
            <h2 class="text-white mt-0">About Us</h2>
            <hr class="divider light my-4">
            <p class="text-white mb-4">Baguio Golf View Apartment and Transient is located at Munoz Drive, KM 4 Asin Road Baguio City. You can go to the beautiful parks downtown within a span of 10-15 minutes depending on the flow of traffic. Staying with us will make you feel at home as we have a complete furniture and kitchen utensils. We also have a hot and cold shower and a strong wifi connection. The only thing you have to bring is your personal things. The best thing in staying at the Baguio Golf View Apartment and Transient is that it is affordable and minutes ride to Asin Hot Spring and BenCab Museum and you can stop and shop along the way for woodcarving souvenir. The highlight of this Transient is the relaxing view of the Pinewoods Golf and Country Club.</p>
            <a class="btn btn-light btn-xl js-scroll-trigger" href="#portfolio">Get Started!</a>
        </div>
    </div>
</div>

Views/Asin/Contact.cshtml
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
            <h2 class="mt-0">Let's Get In Touch!</h2>
            <hr class="divider my-4">
            <p class="text mb-5">Ready to visit Baguio City? Give us a call or send us a message and we will get back to you as soon as possible!</p>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
            <i class="fas fa-phone fa-3x mb-3"></i>
            <div>09354393929 - Globe</div>
            <div>09386466947 - Smart</div>
        </div>
        <div class="col-lg-4 mr-auto text-center">
            <i class="fas fa-envelope fa-3x mb-3"></i>
            <!-- Make sure to change the email address in anchor text AND the link below! -->
            <a class="d-block" href="https://www.facebook.com/Baguio-Golf-View-Apartment-and-Transient-351107875098077/">Click here to message us at facebook</a>
        </div>
    </div>
</div>

Views/Asin/Home.cshtml
<!-- Masthead -->
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">Baguio Golf View Apartment and Transient</h1>
                <hr class="divider my-4">
            </div>
            <div class="col-lg-8 align-self-baseline">
                <p class="text-white-75 font-weight-light mb-5"> </p>
                <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Find Out More</a>
            </div>
        </div>
    </div>
</header>

Views/Asin/Index.cshtml
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Home</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto my-2 my-lg-0">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#about">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#services">Reservation</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Home Section -->
<section id="page-top">
    @await Html.PartialAsync("~/views/Asin/Home.cshtml")
</section>

<!-- AboutUs Section -->
<section class="page-section bg-primary" id="about">
    @await Html.PartialAsync("~/views/Asin/AboutUs.cshtml")
</section>

@*<div class="w3-container w3-black text-black">
    <h2 class="mb-4"> </h2>
</div>
<div class="w3-container w3-black text-black">
    <h2 class="mb-4"> </h2>
</div>*@
@*<div class="w3-container w3-black text-black">
    <h2 class="mb-4"> </h2>
</div>*@
<div>
    @*<input type="button" id="TypeId" value="Test Type" style="z-index:1031;" />
        <input type="button" id="DeleteTypeId" value="Test Type" style="z-index:1031;" />*@
    @*<input type="text" id="InsertTypeText" />
    <input type="button" id="InsertType" value="Add" />
    <select id="types"></select>
    <input type="button" id="DeleteType" value="Delete" />
    <select id="types"></select>
        <input type="button" id="DeleteType" value="Delete" />
    <input type="text" id="UpdateTypeText" />
    <input type="button" id="UpdateType" value="Update" />
    <br />
    <br />
    <input type="text" id="AddGuestText" />
    <input type="button" id="AddGuest" value="Add" />

    <script>
        $(function () {
            $("#InsertType").on("click", function (e) {
                var addType = $("#InsertTypeText").val();
                //alert(addType);
                //alert("working!");
                $.ajax({
                    url: "@Html.Raw(Url.Action("InsertType", "Type"))",
                    Type: "post",
                    data: {
                        name : addType
                    },
                    success: function (data) {
                        console.log(data);
                        loadType();
                    }
                });
            });
            loadType();


            $("#UpdateType").on("click", function (e) {
                var getSelectedType = $("#types").val();
                var editType = $("#UpdateTypeText").val();
                //alert(getSelectedType);
                //alert(editType);
                //alert("working!");
                $.ajax({
                    url: "@Html.Raw(Url.Action("EditTypeById", "Type"))",
                    Type: "post",
                    data: {
                        id: getSelectedType,
                        name : editType
                    },
                    success: function (data) {
                        console.log(data);
                        loadType();
                    }
                });
            });
            loadType();

            function loadType() {
                var optionsSelect = $("#types");
                optionsSelect.empty();
                $.ajax({
                    url: "@Html.Raw(Url.Action("LoadTypes", "Type"))",
                    Type: "post",
                    success: function (data) {
                        var options = data.map(function (val, ind) {
                            return $("<option></option>").val(val.id).html(val.name);
                        });
                        optionsSelect.append(options);
                    }
                });
            }
            $("#DeleteType").on("click", function (e) {
                //alert("working!");
                var removeSelectedType = $("#types").val();
                //alert(removeSelectedType);
                $.ajax({
                    url: "@Html.Raw(Url.Action("DeleteTypeById", "Type"))",
                    Type: "post",
                    data: {
                        Id: removeSelectedType
                    },
                    success: function (data) {
                        console.log(data);
                        loadType();
                    }
                });
            });

        });
    </script>

    <div>
        <input type="button" id="AddGuests" value="Informations" />
    </div>

    <script>
        $(function () {
            $("#AddGuests").on("click", function (e) {
                //alert("working");

                var addGuestFirstName = $("#AddGuestFirstNameText").val();
                var addGuestLastName = $("#AddGuestLastNameText").val();
                var addGuestContactNumber = $("#AddGuestContactNumberText").val();
                var htmlContent = `<div class="container">
<div class="row">
<div class="col-md-6">
<input type="tect" id="AddGuestFirstNameText" placeholder="First Name"/>
<div>
<div class="col-md-6">
<input type="tect" id="AddGuestLastNameText" placeholder="Last Name"/>
<div>
<div class="col-md-6">
<input type="tect" id="AddGuestContactNumberText" placeholder="Contact Number"/>
<div>
</div>`
                Swal.fire({
                    title: 'Guest',
                    html: htmlContent,
                    showCloseButton: true,
                    showCancelButton: true,
                    focusConfirm: false,
                    confirmButtonText: 'Submit',
                    cancelButtonText: 'Cancel',
                }).then((result) => {
                    if (result.value) {
                        addGuestFirstName = $("body").find("#AddGuestFirstNameText").val();
                        addGuestLastName = $("body").find("#AddGuestLastNameText").val();
                        addGuestContactNumber = $("body").find("#AddGuestContactNumberText").val();
                        addGuest(addGuestFirstName, addGuestLastName, addGuestContactNumber);
                    } else if (
                        result.dismiss === Swal.dismissReason.cancel
                    ) {
                        Swal.fire(
                            'Cancelled',
                            '',
                            'error'
                        )
                    }
                })
            });

            function addGuest(addGuestFirstName, addGuestLastName, addGuestContactNumber) {
                $.ajax({
                    url: "@Html.Raw(Url.Action("AddGuest", "Guest"))",
                    Type: "post",
                    data: {
                        firstName: addGuestFirstName,
                        lastName: addGuestLastName,
                        contactNumber: addGuestContactNumber
                    },
                    success: function (data) {
                        console, log(data);
                        Swal.fire(
                            'Submitted',
                            'Your file has been submitted.',
                            'success'
                        );
                    }
                });
            }
        });
    </script>

    <div>
        <input type="button" id="AddGuests2" value="Additional Informations" />
    </div>

    <script>
        $(function () {
            $("#AddGuests2").on("click", function (e) {
                //alert("working");

                var addGuestEmail = $("#AddGuestEmailText").val();
                var addGuestStatus = $("#AddGuestStatusText").val();
                var addGuestComment = $("#AddGuestCommentText").val();
                var htmlContent = `<div class="container">
<div class="row">
<div class="col-md-6">
<input type="tect" id="AddGuestEmailText" placeholder="Email"/>
<div>
<div class="col-md-6">
<input type="tect" id="AddGuestStatusText" placeholder="Status"/>
<div>
<div class="col-md-6">
<input type="tect" id="AddGuestCommentText" placeholder="Comment"/>
<div>
</div>`
                Swal.fire({
                    title: 'Guest',
                    html: htmlContent,
                    showCloseButton: true,
                    showCancelButton: true,
                    focusConfirm: false,
                    confirmButtonText: 'Submit',
                    cancelButtonText: 'Cancel',
                }).then((result) => {
                    if (result.value) {
                        addGuestEmail = $("body").find("#AddGuestEmailText").val();
                        addGuestStatus = $("body").find("#AddGuestStatusText").val();
                        addGuestComment = $("body").find("#AddGuestCommentText").val();
                        addGuest(addGuestEmail, addGuestStatus, addGuestComment);
                    } else if (
                        result.dismiss === Swal.dismissReason.cancel
                    ) {
                        Swal.fire(
                            'Cancelled',
                            '',
                            'error'
                        )
                    }
                })
            });

            function addGuest(addGuestEmail, addGuestStatus, addGuestComment) {
                $.ajax({
                    url: "@Html.Raw(Url.Action("AddGuest", "Guest"))",
                    Type: "post",
                    data: {
                        email: addGuestEmail,
                        status: addGuestStatus,
                        comment: addGuestComment
                    },
                    success: function (data) {
                        console, log(data);
                        Swal.fire(
                            'Submitted',
                            'Your file has been submitted.',
                            'success'
                        );
                    }
                });
            }
        });
    </script>*@

   

</div>
<!-- Portfolio Section -->
<section id="portfolio">
    @await Html.PartialAsync("~/views/Asin/Portfolio.cshtml")
</section>
<!-- Rheeze Gyver B. Kalahi -->
<div class="w3-container w3-black text-black">
    <h2 class="mb-4"> </h2>
</div>
@*<div class="w3-container w3-black text-black">
    <h2 class="mb-4"> </h2>
</div>*@
@*<div class="w3-container w3-black text-black">
    <h2 class="mb-4"> </h2>
</div>*@

<!-- Reservation Section -->
<section class="page-section" id="services">
    @await Html.PartialAsync("~/views/Asin/Reservation.cshtml")
</section>

@*<div class="w3-container w3-black text-black">
    <h2 class="mb-4"> </h2>
</div>*@
@*<div class="w3-container w3-black text-black">
    <h2 class="mb-4"> </h2>
</div>*@
@*<div class="w3-container w3-black text-black">
    <h2 class="mb-4"> </h2>
</div>*@

<!-- Contact Section -->
<section class="page-section bg-primary" id="contact">
    @await Html.PartialAsync("~/views/Asin/Contact.cshtml")
</section>

@*<section class="page-Testimonial">
    @await Html.PartialAsync("~/views/Asin/Testimonial.cshtml")
</section>*@


Views/Asin/Portfolio.cshtml
<div class="container-fluid p-0">
    <div class="row no-gutters">
        <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="~/lib/img/portfolio/fullsize/1.png">
                <img class="img-fluid" src="~/lib/img/portfolio/thumbnails/1.png" alt="">
                <div class="portfolio-box-caption">
                    <div class="project-category text-white-50">
                        Category
                    </div>
                    <div class="project-name">
                        Project Name
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="~/lib/img/portfolio/fullsize/2.jpg">
                <img class="img-fluid" src="~/lib/img/portfolio/thumbnails/2.jpg" alt="">
                <div class="portfolio-box-caption">
                    <div class="project-category text-white-50">
                        Category
                    </div>
                    <div class="project-name">
                        Project Name
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="~/lib/img/portfolio/fullsize/3.jpg">
                <img class="img-fluid" src="~/lib/img/portfolio/thumbnails/3.jpg" alt="">
                <div class="portfolio-box-caption">
                    <div class="project-category text-white-50">
                        Category
                    </div>
                    <div class="project-name">
                        Project Name
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="~/lib/img/portfolio/fullsize/1.png">
                <img class="img-fluid" src="~/lib/img/portfolio/thumbnails/1.png" alt="">
                <div class="portfolio-box-caption">
                    <div class="project-category text-white-50">
                        Category
                    </div>
                    <div class="project-name">
                        Project Name
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="~/lib/img/portfolio/fullsize/2.jpg">
                <img class="img-fluid" src="~/lib/img/portfolio/thumbnails/2.jpg" alt="">
                <div class="portfolio-box-caption">
                    <div class="project-category text-white-50">
                        Category
                    </div>
                    <div class="project-name">
                        Project Name
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="~/lib/img/portfolio/fullsize/3.jpg">
                <img class="img-fluid" src="~/lib/img/portfolio/thumbnails/3.jpg" alt="">
                <div class="portfolio-box-caption p-3">
                    <div class="project-category text-white-50">
                        Category
                    </div>
                    <div class="project-name">
                        Project Name
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>

Views/Asin/Testimonial.cshtml
<style type="text/css">
    body {
        font-family: "Open Sans", sans-serif;
    }

    h2.testimonials {
        color: #333;
        text-align: center;
        text-transform: uppercase;
        font-family: "Roboto", sans-serif;
        font-weight: bold;
        position: relative;
        margin: 25px 0 50px;
    }

        h2.testimonials::after {
            content: "";
            width: 100px;
            position: absolute;
            margin: 0 auto;
            height: 3px;
            background: #ffdc12;
            left: 0;
            right: 0;
            bottom: -10px;
        }

    .carousel {
        width: 650px;
        margin: 0 auto;
        padding-bottom: 50px;
    }

        .carousel .item {
            color: #999;
            font-size: 14px;
            text-align: center;
            overflow: hidden;
            min-height: 340px;
        }

            .carousel .item a {
                color: #eb7245;
            }

        .carousel .img-box {
            width: 145px;
            height: 145px;
            margin: 0 auto;
            border-radius: 50%;
        }

            .carousel .img-box img {
                width: 100%;
                height: 100%;
                display: block;
                border-radius: 50%;
            }

        .carousel .testimonial {
            padding: 30px 0 10px;
        }

        .carousel .overview {
            text-align: center;
            padding-bottom: 5px;
        }

            .carousel .overview b {
                color: #333;
                font-size: 15px;
                text-transform: uppercase;
                display: block;
                padding-bottom: 5px;
            }

        .carousel .star-rating i {
            font-size: 18px;
            color: #ffdc12;
        }

        .carousel .carousel-control {
            width: 30px;
            height: 30px;
            border-radius: 50%;
            background: #999;
            text-shadow: none;
            top: 4px;
        }

    .carousel-control i {
        font-size: 20px;
        margin-right: 2px;
    }

    .carousel-control.left {
        left: auto;
        right: 40px;
    }

    .carousel-control.right i {
        margin-right: -2px;
    }

    .carousel .carousel-indicators {
        bottom: 15px;
    }

    .carousel-indicators li, .carousel-indicators li.active {
        width: 11px;
        height: 11px;
        margin: 1px 5px;
        border-radius: 50%;
    }

    .carousel-indicators li {
        background: #e2e2e2;
        border-color: transparent;
    }

        .carousel-indicators li.active {
            border: none;
            background: #888;
        }
</style>
<h2 class="testimonials">Testimonials</h2>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Carousel indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <!-- Wrapper for carousel items -->
    <div class="carousel-inner">
        <div class="item carousel-item active">
            <div class="img-box"><img src="~/images/3.jpg" alt=""></div>
            <p class="testimonial">
                I just wanted to share a quick note and let you know that you guys do a really good job. I’m glad I decided to book with you. It’s really great how accomodating you are. I never have any problem at all.
                Thanks, guys!
            </p>
            <p class="overview"><b>Michael Holz</b>Seo Analyst at <a href="#">OsCorp Tech.</a></p>
            <div class="star-rating">
                <ul class="list-inline">
                    <li class="list-inline-item"><i class="fa fa-star"></i></li>
                    <li class="list-inline-item"><i class="fa fa-star"></i></li>
                    <li class="list-inline-item"><i class="fa fa-star"></i></li>
                    <li class="list-inline-item"><i class="fa fa-star"></i></li>
                    <li class="list-inline-item"><i class="fa fa-star-o"></i></li>
                </ul>
            </div>
        </div>
        <div class="item carousel-item">
            <div class="img-box"><img src="~/images/1.jpg" alt=""></div>
            <p class="testimonial">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Vestibulum idac nisl bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet.</p>
            <p class="overview"><b>Paula Wilson</b>Media Analyst at <a href="#">SkyNet Inc.</a></p>
            <div class="star-rating">
                <ul class="list-inline">
                    <li class="list-inline-item"><i class="fa fa-star"></i></li>
                    <li class="list-inline-item"><i class="fa fa-star"></i></li>
                    <li class="list-inline-item"><i class="fa fa-star"></i></li>
                    <li class="list-inline-item"><i class="fa fa-star"></i></li>
                    <li class="list-inline-item"><i class="fa fa-star-o"></i></li>
                </ul>
            </div>
        </div>
        <div class="item carousel-item">
            <div class="img-box"><img src="~/images/2.jpg" alt=""></div>
            <p class="testimonial">Vestibulum quis quam ut magna consequat faucibus. Pellentesque eget nisi a mi suscipit tincidunt. Utmtc tempus dictum risus. Pellentesque viverra sagittis quam at mattis. Suspendisse potenti. Aliquam sit amet gravida nibh, facilisis gravida odio. Phasellus auctor velit.</p>
            <p class="overview"><b>Antonio Moreno</b>Web Developer at <a href="#">Circle Ltd.</a></p>
            <div class="star-rating">
                <ul class="list-inline">
                    <li class="list-inline-item"><i class="fa fa-star"></i></li>
                    <li class="list-inline-item"><i class="fa fa-star"></i></li>
                    <li class="list-inline-item"><i class="fa fa-star"></i></li>
                    <li class="list-inline-item"><i class="fa fa-star"></i></li>
                    <li class="list-inline-item"><i class="fa fa-star-half-o"></i></li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Carousel controls -->
    <a class="carousel-control left carousel-control-prev" href="#myCarousel" data-slide="prev">
        <i class="fa fa-angle-left"></i>
    </a>
    <a class="carousel-control right carousel-control-next" href="#myCarousel" data-slide="next">
        <i class="fa fa-angle-right"></i>
    </a>
</div>